package dev.zt64.ffmpegkt.codec

import dev.zt64.ffmpegkt.avutil.MediaType
import kotlin.jvm.JvmInline

/**
 * Codec IDs are an integer value that identifies a codec.
 *
 * @constructor Should not be used directly. Use the predefined values in the companion object.
 */
@JvmInline
public value class CodecID(public val num: Int) {
    @Suppress("ktlint:standard:backing-property-naming", "ObjectPropertyName", "SpellCheckingInspection")
    public companion object {
        public val NONE: CodecID = CodecID(0)

        /* video codecs */
        public val MPEG1VIDEO: CodecID = CodecID(1)

        /** preferred ID for MPEG-1/2 video decoding */
        public val MPEG2VIDEO: CodecID = CodecID(2)
        public val H261: CodecID = CodecID(3)
        public val H263: CodecID = CodecID(4)
        public val RV10: CodecID = CodecID(5)
        public val RV20: CodecID = CodecID(6)
        public val MJPEG: CodecID = CodecID(7)
        public val MJPEGB: CodecID = CodecID(8)
        public val LJPEG: CodecID = CodecID(9)
        public val SP5X: CodecID = CodecID(10)
        public val JPEGLS: CodecID = CodecID(11)
        public val MPEG4: CodecID = CodecID(12)

        public val RAWVIDEO: CodecID = CodecID(13)
        public val MSMPEG4V1: CodecID = CodecID(14)
        public val MSMPEG4V2: CodecID = CodecID(15)
        public val MSMPEG4V3: CodecID = CodecID(16)
        public val WMV1: CodecID = CodecID(17)
        public val WMV2: CodecID = CodecID(18)
        public val H263P: CodecID = CodecID(19)
        public val H263I: CodecID = CodecID(20)
        public val FLV1: CodecID = CodecID(21)
        public val SVQ1: CodecID = CodecID(22)
        public val SVQ3: CodecID = CodecID(23)
        public val DVVIDEO: CodecID = CodecID(24)
        public val HUFFYUV: CodecID = CodecID(25)
        public val CYUV: CodecID = CodecID(26)
        public val H264: CodecID = CodecID(27)
        public val INDEO3: CodecID = CodecID(28)
        public val VP3: CodecID = CodecID(29)
        public val THEORA: CodecID = CodecID(30)
        public val ASV1: CodecID = CodecID(31)
        public val ASV2: CodecID = CodecID(32)
        public val FFV1: CodecID = CodecID(33)
        public val _4XM: CodecID = CodecID(34)
        public val VCR1: CodecID = CodecID(35)
        public val CLJR: CodecID = CodecID(36)
        public val MDEC: CodecID = CodecID(37)
        public val ROQ: CodecID = CodecID(38)
        public val INTERPLAY_VIDEO: CodecID = CodecID(39)
        public val XAN_WC3: CodecID = CodecID(40)
        public val XAN_WC4: CodecID = CodecID(41)
        public val RPZA: CodecID = CodecID(42)
        public val CINEPAK: CodecID = CodecID(43)
        public val WS_VQA: CodecID = CodecID(44)
        public val MSRLE: CodecID = CodecID(45)
        public val MSVIDEO1: CodecID = CodecID(46)
        public val IDCIN: CodecID = CodecID(47)
        public val _8BPS: CodecID = CodecID(48)
        public val SMC: CodecID = CodecID(49)
        public val FLIC: CodecID = CodecID(50)
        public val TRUEMOTION1: CodecID = CodecID(51)
        public val VMDVIDEO: CodecID = CodecID(52)
        public val MSZH: CodecID = CodecID(53)
        public val ZLIB: CodecID = CodecID(54)
        public val QTRLE: CodecID = CodecID(55)
        public val SNOW: CodecID = CodecID(56)
        public val TSCC: CodecID = CodecID(57)
        public val ULTI: CodecID = CodecID(58)
        public val QDRAW: CodecID = CodecID(59)
        public val VIXL: CodecID = CodecID(60)
        public val QPEG: CodecID = CodecID(61)
        public val XVID: CodecID = CodecID(62)
        public val PNG: CodecID = CodecID(63)
        public val PPM: CodecID = CodecID(64)
        public val PBM: CodecID = CodecID(65)
        public val PGM: CodecID = CodecID(66)
        public val PGMYUV: CodecID = CodecID(67)
        public val PAM: CodecID = CodecID(68)
        public val FFVHUFF: CodecID = CodecID(69)
        public val RV30: CodecID = CodecID(70)
        public val RV40: CodecID = CodecID(71)
        public val VC1: CodecID = CodecID(72)
        public val WMV3: CodecID = CodecID(73)
        public val LOCO: CodecID = CodecID(74)
        public val WNV1: CodecID = CodecID(75)
        public val AASC: CodecID = CodecID(76)
        public val INDEO2: CodecID = CodecID(77)
        public val FRAPS: CodecID = CodecID(78)
        public val TRUEMOTION2: CodecID = CodecID(79)
        public val BMP: CodecID = CodecID(80)
        public val CSCD: CodecID = CodecID(81)
        public val MMVIDEO: CodecID = CodecID(82)
        public val ZMBV: CodecID = CodecID(83)
        public val AVS: CodecID = CodecID(84)
        public val SMACKVIDEO: CodecID = CodecID(85)
        public val NUV: CodecID = CodecID(86)
        public val KMVC: CodecID = CodecID(87)
        public val FLASHSV: CodecID = CodecID(88)
        public val CAVS: CodecID = CodecID(89)
        public val JPEG2000: CodecID = CodecID(90)
        public val VMNC: CodecID = CodecID(91)
        public val VP5: CodecID = CodecID(92)
        public val VP6: CodecID = CodecID(93)
        public val VP6F: CodecID = CodecID(94)
        public val TARGA: CodecID = CodecID(95)
        public val DSICINVIDEO: CodecID = CodecID(96)
        public val TIERTEXSEQVIDEO: CodecID = CodecID(97)
        public val TIFF: CodecID = CodecID(98)
        public val GIF: CodecID = CodecID(99)
        public val FFH264: CodecID = CodecID(100)
        public val DXA: CodecID = CodecID(101)
        public val DNXHD: CodecID = CodecID(102)
        public val THP: CodecID = CodecID(103)
        public val SGI: CodecID = CodecID(104)
        public val C93: CodecID = CodecID(105)
        public val BETHSOFTVID: CodecID = CodecID(106)
        public val PTX: CodecID = CodecID(107)
        public val TXD: CodecID = CodecID(108)
        public val VP6A: CodecID = CodecID(109)
        public val AMV: CodecID = CodecID(110)
        public val VB: CodecID = CodecID(111)
        public val PCX: CodecID = CodecID(112)
        public val SUNRAST: CodecID = CodecID(113)
        public val INDEO4: CodecID = CodecID(114)
        public val INDEO5: CodecID = CodecID(115)
        public val MIMIC: CodecID = CodecID(116)
        public val RL2: CodecID = CodecID(117)
        public val _8SVX_EXP: CodecID = CodecID(118)
        public val _8SVX_FIB: CodecID = CodecID(119)
        public val ESCAPE124: CodecID = CodecID(120)
        public val DIRAC: CodecID = CodecID(121)
        public val BFI: CodecID = CodecID(122)
        public val CMV: CodecID = CodecID(123)
        public val MOTIONPIXELS: CodecID = CodecID(124)
        public val TGV: CodecID = CodecID(125)
        public val TGQ: CodecID = CodecID(126)
        public val TQI: CodecID = CodecID(127)
        public val AURA: CodecID = CodecID(128)
        public val AURA2: CodecID = CodecID(129)
        public val V210X: CodecID = CodecID(130)
        public val TMV: CodecID = CodecID(131)
        public val V210: CodecID = CodecID(132)
        public val DPX: CodecID = CodecID(133)
        public val MAD: CodecID = CodecID(134)
        public val FRWU: CodecID = CodecID(135)
        public val FLASHSV2: CodecID = CodecID(136)
        public val CDGRAPHICS: CodecID = CodecID(137)
        public val R210: CodecID = CodecID(138)
        public val ANM: CodecID = CodecID(139)
        public val BINKVIDEO: CodecID = CodecID(140)
        public val IFF_ILBM: CodecID = CodecID(141)
        public val IFF_BYTERUN1: CodecID = CodecID(142)
        public val KGV1: CodecID = CodecID(143)
        public val YOP: CodecID = CodecID(144)
        public val VP8: CodecID = CodecID(145)

        /* various PCM "codecs" */
        public val PCM_S16LE: CodecID = CodecID(0x10000)
        public val PCM_S16BE: CodecID = CodecID(0x10001)
        public val PCM_U16LE: CodecID = CodecID(0x10002)
        public val PCM_U16BE: CodecID = CodecID(0x10003)
        public val PCM_S8: CodecID = CodecID(0x10004)
        public val PCM_U8: CodecID = CodecID(0x10005)
        public val PCM_MULAW: CodecID = CodecID(0x10006)
        public val PCM_ALAW: CodecID = CodecID(0x10007)
        public val PCM_S32LE: CodecID = CodecID(0x10008)
        public val PCM_S32BE: CodecID = CodecID(0x10009)
        public val PCM_U32LE: CodecID = CodecID(0x1000A)
        public val PCM_U32BE: CodecID = CodecID(0x1000B)
        public val PCM_S24LE: CodecID = CodecID(0x1000C)
        public val PCM_S24BE: CodecID = CodecID(0x1000D)
        public val PCM_U24LE: CodecID = CodecID(0x1000E)
        public val PCM_U24BE: CodecID = CodecID(0x1000F)
        public val PCM_S24DAUD: CodecID = CodecID(0x10010)
        public val PCM_ZORK: CodecID = CodecID(0x10011)
        public val PCM_S16LE_PLANAR: CodecID = CodecID(0x10012)
        public val PCM_DVD: CodecID = CodecID(0x10013)
        public val PCM_F32BE: CodecID = CodecID(0x10014)
        public val PCM_F32LE: CodecID = CodecID(0x10015)
        public val PCM_F64BE: CodecID = CodecID(0x10016)
        public val PCM_F64LE: CodecID = CodecID(0x10017)
        public val PCM_BLURAY: CodecID = CodecID(0x10018)

        /* various ADPCM codecs */
        public val ADPCM_IMA_QT: CodecID = CodecID(0x11000)
        public val ADPCM_IMA_WAV: CodecID = CodecID(0x11001)
        public val ADPCM_IMA_DK3: CodecID = CodecID(0x11002)
        public val ADPCM_IMA_DK4: CodecID = CodecID(0x11003)
        public val ADPCM_IMA_WS: CodecID = CodecID(0x11004)
        public val ADPCM_IMA_SMJPEG: CodecID = CodecID(0x11005)
        public val ADPCM_MS: CodecID = CodecID(0x11006)
        public val ADPCM_4XM: CodecID = CodecID(0x11007)
        public val ADPCM_XA: CodecID = CodecID(0x11008)
        public val ADPCM_ADX: CodecID = CodecID(0x11009)
        public val ADPCM_EA: CodecID = CodecID(0x1100A)
        public val ADPCM_G726: CodecID = CodecID(0x1100B)
        public val ADPCM_CT: CodecID = CodecID(0x1100C)
        public val ADPCM_SWF: CodecID = CodecID(0x1100D)
        public val ADPCM_YAMAHA: CodecID = CodecID(0x1100E)
        public val ADPCM_SBPRO_4: CodecID = CodecID(0x1100F)
        public val ADPCM_SBPRO_3: CodecID = CodecID(0x11010)
        public val ADPCM_SBPRO_2: CodecID = CodecID(0x11011)
        public val ADPCM_THP: CodecID = CodecID(0x11012)
        public val ADPCM_IMA_AMV: CodecID = CodecID(0x11013)
        public val ADPCM_EA_R1: CodecID = CodecID(0x11014)
        public val ADPCM_EA_R3: CodecID = CodecID(0x11015)
        public val ADPCM_EA_R2: CodecID = CodecID(0x11016)
        public val ADPCM_IMA_EA_SEAD: CodecID = CodecID(0x11017)
        public val ADPCM_IMA_EA_EACS: CodecID = CodecID(0x11018)
        public val ADPCM_EA_XAS: CodecID = CodecID(0x11019)
        public val ADPCM_EA_MAXIS_XA: CodecID = CodecID(0x1101A)
        public val ADPCM_IMA_ISS: CodecID = CodecID(0x1101B)

        /* AMR */
        public val AMR_NB: CodecID = CodecID(0x12000)
        public val AMR_WB: CodecID = CodecID(0x12001)

        /* RealAudio codecs*/
        public val RA_144: CodecID = CodecID(0x13000)
        public val RA_288: CodecID = CodecID(0x13001)

        /* various DPCM codecs */
        public val ROQ_DPCM: CodecID = CodecID(0x14000)
        public val INTERPLAY_DPCM: CodecID = CodecID(0x14001)
        public val XAN_DPCM: CodecID = CodecID(0x14002)
        public val SOL_DPCM: CodecID = CodecID(0x14003)

        /* audio codecs */
        public val MP2: CodecID = CodecID(0x15000)

        /** preferred ID for decoding MPEG audio layer 1, 2 or 3 */
        public val MP3: CodecID = CodecID(0x15001)
        public val AAC: CodecID = CodecID(0x15002)
        public val AC3: CodecID = CodecID(0x15003)
        public val DTS: CodecID = CodecID(0x15004)
        public val VORBIS: CodecID = CodecID(0x15005)
        public val DVAUDIO: CodecID = CodecID(0x15006)
        public val WMAV1: CodecID = CodecID(0x15007)
        public val WMAV2: CodecID = CodecID(0x15008)
        public val MACE3: CodecID = CodecID(0x15009)
        public val MACE6: CodecID = CodecID(0x1500A)
        public val VMDAUDIO: CodecID = CodecID(0x1500B)
        public val SONIC: CodecID = CodecID(0x1500C)
        public val SONIC_LS: CodecID = CodecID(0x1500D)
        public val FLAC: CodecID = CodecID(0x1500E)
        public val MP3ADU: CodecID = CodecID(0x1500F)
        public val MP3ON4: CodecID = CodecID(0x15010)
        public val SHORTEN: CodecID = CodecID(0x15011)
        public val ALAC: CodecID = CodecID(0x15012)
        public val WESTWOOD_SND1: CodecID = CodecID(0x15013)

        /** as in Berlin toast format */
        public val GSM: CodecID = CodecID(0x15014)
        public val QDM2: CodecID = CodecID(0x15015)
        public val COOK: CodecID = CodecID(0x15016)
        public val TRUESPEECH: CodecID = CodecID(0x15017)
        public val TTA: CodecID = CodecID(0x15018)
        public val SMACKAUDIO: CodecID = CodecID(0x15019)
        public val QCELP: CodecID = CodecID(0x1501A)
        public val WAVPACK: CodecID = CodecID(0x1501B)
        public val DSICINAUDIO: CodecID = CodecID(0x1501C)
        public val IMC: CodecID = CodecID(0x1501D)
        public val MUSEPACK7: CodecID = CodecID(0x1501E)
        public val MLP: CodecID = CodecID(0x1501F)

        /** As found in WAV */
        public val GSM_MS: CodecID = CodecID(0x15020)
        public val ATRAC3: CodecID = CodecID(0x15021)
        public val VOXWARE: CodecID = CodecID(0x15022)
        public val APE: CodecID = CodecID(0x15023)
        public val NELLYMOSER: CodecID = CodecID(0x15024)
        public val MUSEPACK8: CodecID = CodecID(0x15025)
        public val SPEEX: CodecID = CodecID(0x15026)
        public val WMAVOICE: CodecID = CodecID(0x15027)
        public val WMAPRO: CodecID = CodecID(0x15028)
        public val WMALOSSLESS: CodecID = CodecID(0x15029)
        public val ATRAC3P: CodecID = CodecID(0x1502A)
        public val EAC3: CodecID = CodecID(0x1502B)
        public val SIPR: CodecID = CodecID(0x1502C)
        public val MP1: CodecID = CodecID(0x1502D)
        public val TWINVQ: CodecID = CodecID(0x1502E)
        public val TRUEHD: CodecID = CodecID(0x1502F)
        public val MP4ALS: CodecID = CodecID(0x15030)
        public val ATRAC1: CodecID = CodecID(0x15031)
        public val BINKAUDIO_RDFT: CodecID = CodecID(0x15032)
        public val BINKAUDIO_DCT: CodecID = CodecID(0x15033)

        /* subtitle codecs */
        public val DVD_SUBTITLE: CodecID = CodecID(0x17000)
        public val DVB_SUBTITLE: CodecID = CodecID(0x17001)
        public val TEXT: CodecID = CodecID(0x17002)
        public val XSUB: CodecID = CodecID(0x17003)
        public val SSA: CodecID = CodecID(0x17004)
        public val MOV_TEXT: CodecID = CodecID(0x17005)
        public val HDMV_PGS_SUBTITLE: CodecID = CodecID(0x17006)
        public val DVB_TELETEXT: CodecID = CodecID(0x17007)

        /* other specific kind of codecs (generally used for attachments) */
        public val TTF: CodecID = CodecID(0x18000)
        public val PROBE: CodecID = CodecID(0x19000)

        // _FAKE_ codec to indicate a raw MPEG-2 TS stream (only used by libavformat)
        public val MPEG2TS: CodecID = CodecID(0x20000)
    }

    override fun toString(): String = name
}

public expect val CodecID.type: MediaType
public expect val CodecID.name: String