package dev.zt64.ffmpegkt.avutil

public enum class AVPixelFormat(public val value: Int) {
    AV_PIX_FMT_NONE(-1),

    AV_PIX_FMT_YUV420P(0),

    AV_PIX_FMT_YUYV422(1),

    AV_PIX_FMT_RGB24(2),

    AV_PIX_FMT_BGR24(3),

    AV_PIX_FMT_YUV422P(4),

    AV_PIX_FMT_YUV444P(5),

    AV_PIX_FMT_YUV410P(6),

    AV_PIX_FMT_YUV411P(7),

    AV_PIX_FMT_GRAY8(8),

    AV_PIX_FMT_MONOWHITE(9),

    AV_PIX_FMT_MONOBLACK(10),

    AV_PIX_FMT_PAL8(11),

    AV_PIX_FMT_YUVJ420P(12),

    AV_PIX_FMT_YUVJ422P(13),

    AV_PIX_FMT_YUVJ444P(14),

    AV_PIX_FMT_UYVY422(15),

    AV_PIX_FMT_UYYVYY411(16),

    AV_PIX_FMT_BGR8(17),

    AV_PIX_FMT_BGR4(18),

    AV_PIX_FMT_BGR4_BYTE(19),

    AV_PIX_FMT_RGB8(20),

    AV_PIX_FMT_RGB4(21),

    AV_PIX_FMT_RGB4_BYTE(22),

    AV_PIX_FMT_NV12(23),

    AV_PIX_FMT_NV21(24),

    AV_PIX_FMT_ARGB(25),

    AV_PIX_FMT_RGBA(26),

    AV_PIX_FMT_ABGR(27),

    AV_PIX_FMT_BGRA(28),

    AV_PIX_FMT_GRAY16BE(29),

    AV_PIX_FMT_GRAY16LE(30),

    AV_PIX_FMT_YUV440P(31),

    AV_PIX_FMT_YUVJ440P(32),

    AV_PIX_FMT_YUVA420P(33),

    AV_PIX_FMT_RGB48BE(34),

    AV_PIX_FMT_RGB48LE(35),

    AV_PIX_FMT_RGB565BE(36),

    AV_PIX_FMT_RGB565LE(37),

    AV_PIX_FMT_RGB555BE(38),

    AV_PIX_FMT_RGB555LE(39),

    AV_PIX_FMT_BGR565BE(40),

    AV_PIX_FMT_BGR565LE(41),

    AV_PIX_FMT_BGR555BE(42),

    AV_PIX_FMT_BGR555LE(43),

    AV_PIX_FMT_VAAPI(44),

    AV_PIX_FMT_YUV420P16LE(45),

    AV_PIX_FMT_YUV420P16BE(46),

    AV_PIX_FMT_YUV422P16LE(47),

    AV_PIX_FMT_YUV422P16BE(48),

    AV_PIX_FMT_YUV444P16LE(49),

    AV_PIX_FMT_YUV444P16BE(50),

    AV_PIX_FMT_DXVA2_VLD(51),

    AV_PIX_FMT_RGB444LE(52),

    AV_PIX_FMT_RGB444BE(53),

    AV_PIX_FMT_BGR444LE(54),

    AV_PIX_FMT_BGR444BE(55),

    AV_PIX_FMT_YA8(56),

    AV_PIX_FMT_Y400A(AV_PIX_FMT_YA8.value),

    AV_PIX_FMT_GRAY8A(AV_PIX_FMT_YA8.value),

    AV_PIX_FMT_BGR48BE(AV_PIX_FMT_YA8.value + 1),

    AV_PIX_FMT_BGR48LE(AV_PIX_FMT_YA8.value + 2),

    AV_PIX_FMT_YUV420P9BE(AV_PIX_FMT_YA8.value + 3),

    AV_PIX_FMT_YUV420P9LE(AV_PIX_FMT_YA8.value + 4),

    AV_PIX_FMT_YUV420P10BE(AV_PIX_FMT_YA8.value + 5),

    AV_PIX_FMT_YUV420P10LE(AV_PIX_FMT_YA8.value + 6),

    AV_PIX_FMT_YUV422P10BE(AV_PIX_FMT_YA8.value + 7),

    AV_PIX_FMT_YUV422P10LE(AV_PIX_FMT_YA8.value + 8),

    AV_PIX_FMT_YUV444P9BE(AV_PIX_FMT_YA8.value + 9),

    AV_PIX_FMT_YUV444P9LE(AV_PIX_FMT_YA8.value + 10),

    AV_PIX_FMT_YUV444P10BE(AV_PIX_FMT_YA8.value + 11),

    AV_PIX_FMT_YUV444P10LE(AV_PIX_FMT_YA8.value + 12),

    AV_PIX_FMT_YUV422P9BE(AV_PIX_FMT_YA8.value + 13),

    AV_PIX_FMT_YUV422P9LE(AV_PIX_FMT_YA8.value + 14),

    AV_PIX_FMT_GBRP(AV_PIX_FMT_YA8.value + 15),

    AV_PIX_FMT_GBR24P(AV_PIX_FMT_GBRP.value),

    AV_PIX_FMT_GBRP9BE(AV_PIX_FMT_GBRP.value + 1),

    AV_PIX_FMT_GBRP9LE(AV_PIX_FMT_GBRP.value + 2),

    AV_PIX_FMT_GBRP10BE(AV_PIX_FMT_GBRP.value + 3),

    AV_PIX_FMT_GBRP10LE(AV_PIX_FMT_GBRP.value + 4),

    AV_PIX_FMT_GBRP16BE(AV_PIX_FMT_GBRP.value + 5),

    AV_PIX_FMT_GBRP16LE(AV_PIX_FMT_GBRP.value + 6),

    AV_PIX_FMT_YUVA422P(AV_PIX_FMT_GBRP.value + 7),

    AV_PIX_FMT_YUVA444P(AV_PIX_FMT_GBRP.value + 8),

    AV_PIX_FMT_YUVA420P9BE(AV_PIX_FMT_GBRP.value + 9),

    AV_PIX_FMT_YUVA420P9LE(AV_PIX_FMT_GBRP.value + 10),

    AV_PIX_FMT_YUVA422P9BE(AV_PIX_FMT_GBRP.value + 11),

    AV_PIX_FMT_YUVA422P9LE(AV_PIX_FMT_GBRP.value + 12),

    AV_PIX_FMT_YUVA444P9BE(AV_PIX_FMT_GBRP.value + 13),

    AV_PIX_FMT_YUVA444P9LE(AV_PIX_FMT_GBRP.value + 14),

    AV_PIX_FMT_YUVA420P10BE(AV_PIX_FMT_GBRP.value + 15),

    AV_PIX_FMT_YUVA420P10LE(AV_PIX_FMT_GBRP.value + 16),

    AV_PIX_FMT_YUVA422P10BE(AV_PIX_FMT_GBRP.value + 17),

    AV_PIX_FMT_YUVA422P10LE(AV_PIX_FMT_GBRP.value + 18),

    AV_PIX_FMT_YUVA444P10BE(AV_PIX_FMT_GBRP.value + 19),

    AV_PIX_FMT_YUVA444P10LE(AV_PIX_FMT_GBRP.value + 20),

    AV_PIX_FMT_YUVA420P16BE(AV_PIX_FMT_GBRP.value + 21),

    AV_PIX_FMT_YUVA420P16LE(AV_PIX_FMT_GBRP.value + 22),

    AV_PIX_FMT_YUVA422P16BE(AV_PIX_FMT_GBRP.value + 23),

    AV_PIX_FMT_YUVA422P16LE(AV_PIX_FMT_GBRP.value + 24),

    AV_PIX_FMT_YUVA444P16BE(AV_PIX_FMT_GBRP.value + 25),

    AV_PIX_FMT_YUVA444P16LE(AV_PIX_FMT_GBRP.value + 26),

    AV_PIX_FMT_VDPAU(AV_PIX_FMT_GBRP.value + 27),

    AV_PIX_FMT_XYZ12LE(AV_PIX_FMT_GBRP.value + 28),

    AV_PIX_FMT_XYZ12BE(AV_PIX_FMT_GBRP.value + 29),

    AV_PIX_FMT_NV16(AV_PIX_FMT_GBRP.value + 30),

    AV_PIX_FMT_NV20LE(AV_PIX_FMT_GBRP.value + 31),

    AV_PIX_FMT_NV20BE(AV_PIX_FMT_GBRP.value + 32),

    AV_PIX_FMT_RGBA64BE(AV_PIX_FMT_GBRP.value + 33),

    AV_PIX_FMT_RGBA64LE(AV_PIX_FMT_GBRP.value + 34),

    AV_PIX_FMT_BGRA64BE(AV_PIX_FMT_GBRP.value + 35),

    AV_PIX_FMT_BGRA64LE(AV_PIX_FMT_GBRP.value + 36),

    AV_PIX_FMT_YVYU422(AV_PIX_FMT_GBRP.value + 37),

    AV_PIX_FMT_YA16BE(AV_PIX_FMT_GBRP.value + 38),

    AV_PIX_FMT_YA16LE(AV_PIX_FMT_GBRP.value + 39),

    AV_PIX_FMT_GBRAP(AV_PIX_FMT_GBRP.value + 40),

    AV_PIX_FMT_GBRAP16BE(AV_PIX_FMT_GBRP.value + 41),

    AV_PIX_FMT_GBRAP16LE(AV_PIX_FMT_GBRP.value + 42),

    AV_PIX_FMT_QSV(AV_PIX_FMT_GBRP.value + 43),

    AV_PIX_FMT_MMAL(AV_PIX_FMT_GBRP.value + 44),

    AV_PIX_FMT_D3D11VA_VLD(AV_PIX_FMT_GBRP.value + 45),

    AV_PIX_FMT_CUDA(AV_PIX_FMT_GBRP.value + 46),

    AV_PIX_FMT_0RGB(AV_PIX_FMT_GBRP.value + 47),

    AV_PIX_FMT_RGB0(AV_PIX_FMT_GBRP.value + 48),

    AV_PIX_FMT_0BGR(AV_PIX_FMT_GBRP.value + 49),

    AV_PIX_FMT_BGR0(AV_PIX_FMT_GBRP.value + 50),

    AV_PIX_FMT_YUV420P12BE(AV_PIX_FMT_GBRP.value + 51),

    AV_PIX_FMT_YUV420P12LE(AV_PIX_FMT_GBRP.value + 52),

    AV_PIX_FMT_YUV420P14BE(AV_PIX_FMT_GBRP.value + 53),

    AV_PIX_FMT_YUV420P14LE(AV_PIX_FMT_GBRP.value + 54),

    AV_PIX_FMT_YUV422P12BE(AV_PIX_FMT_GBRP.value + 55),

    AV_PIX_FMT_YUV422P12LE(AV_PIX_FMT_GBRP.value + 56),

    AV_PIX_FMT_YUV422P14BE(AV_PIX_FMT_GBRP.value + 57),

    AV_PIX_FMT_YUV422P14LE(AV_PIX_FMT_GBRP.value + 58),

    AV_PIX_FMT_YUV444P12BE(AV_PIX_FMT_GBRP.value + 59),

    AV_PIX_FMT_YUV444P12LE(AV_PIX_FMT_GBRP.value + 60),

    AV_PIX_FMT_YUV444P14BE(AV_PIX_FMT_GBRP.value + 61),

    AV_PIX_FMT_YUV444P14LE(AV_PIX_FMT_GBRP.value + 62),

    AV_PIX_FMT_GBRP12BE(AV_PIX_FMT_GBRP.value + 63),

    AV_PIX_FMT_GBRP12LE(AV_PIX_FMT_GBRP.value + 64),

    AV_PIX_FMT_GBRP14BE(AV_PIX_FMT_GBRP.value + 65),

    AV_PIX_FMT_GBRP14LE(AV_PIX_FMT_GBRP.value + 66),

    AV_PIX_FMT_YUVJ411P(AV_PIX_FMT_GBRP.value + 67),

    AV_PIX_FMT_BAYER_BGGR8(AV_PIX_FMT_GBRP.value + 68),

    AV_PIX_FMT_BAYER_RGGB8(AV_PIX_FMT_GBRP.value + 69),

    AV_PIX_FMT_BAYER_GBRG8(AV_PIX_FMT_GBRP.value + 70),

    AV_PIX_FMT_BAYER_GRBG8(AV_PIX_FMT_GBRP.value + 71),

    AV_PIX_FMT_BAYER_BGGR16LE(AV_PIX_FMT_GBRP.value + 72),

    AV_PIX_FMT_BAYER_BGGR16BE(AV_PIX_FMT_GBRP.value + 73),

    AV_PIX_FMT_BAYER_RGGB16LE(AV_PIX_FMT_GBRP.value + 74),

    AV_PIX_FMT_BAYER_RGGB16BE(AV_PIX_FMT_GBRP.value + 75),

    AV_PIX_FMT_BAYER_GBRG16LE(AV_PIX_FMT_GBRP.value + 76),

    AV_PIX_FMT_BAYER_GBRG16BE(AV_PIX_FMT_GBRP.value + 77),

    AV_PIX_FMT_BAYER_GRBG16LE(AV_PIX_FMT_GBRP.value + 78),

    AV_PIX_FMT_BAYER_GRBG16BE(AV_PIX_FMT_GBRP.value + 79),

    AV_PIX_FMT_XVMC(AV_PIX_FMT_GBRP.value + 80),

    AV_PIX_FMT_YUV440P10LE(AV_PIX_FMT_GBRP.value + 81),

    AV_PIX_FMT_YUV440P10BE(AV_PIX_FMT_GBRP.value + 82),

    AV_PIX_FMT_YUV440P12LE(AV_PIX_FMT_GBRP.value + 83),

    AV_PIX_FMT_YUV440P12BE(AV_PIX_FMT_GBRP.value + 84),

    AV_PIX_FMT_AYUV64LE(AV_PIX_FMT_GBRP.value + 85),

    AV_PIX_FMT_AYUV64BE(AV_PIX_FMT_GBRP.value + 86),

    AV_PIX_FMT_VIDEOTOOLBOX(AV_PIX_FMT_GBRP.value + 87),

    AV_PIX_FMT_P010LE(AV_PIX_FMT_GBRP.value + 88),

    AV_PIX_FMT_P010BE(AV_PIX_FMT_GBRP.value + 89),

    AV_PIX_FMT_GBRAP12BE(AV_PIX_FMT_GBRP.value + 90),

    AV_PIX_FMT_GBRAP12LE(AV_PIX_FMT_GBRP.value + 91),

    AV_PIX_FMT_GBRAP10BE(AV_PIX_FMT_GBRP.value + 92),

    AV_PIX_FMT_GBRAP10LE(AV_PIX_FMT_GBRP.value + 93),

    AV_PIX_FMT_MEDIACODEC(AV_PIX_FMT_GBRP.value + 94),

    AV_PIX_FMT_GRAY12BE(AV_PIX_FMT_GBRP.value + 95),

    AV_PIX_FMT_GRAY12LE(AV_PIX_FMT_GBRP.value + 96),

    AV_PIX_FMT_GRAY10BE(AV_PIX_FMT_GBRP.value + 97),

    AV_PIX_FMT_GRAY10LE(AV_PIX_FMT_GBRP.value + 98),

    AV_PIX_FMT_P016LE(AV_PIX_FMT_GBRP.value + 99),

    AV_PIX_FMT_P016BE(AV_PIX_FMT_GBRP.value + 100),

    AV_PIX_FMT_D3D11(AV_PIX_FMT_GBRP.value + 101),

    AV_PIX_FMT_GRAY9BE(AV_PIX_FMT_GBRP.value + 102),

    AV_PIX_FMT_GRAY9LE(AV_PIX_FMT_GBRP.value + 103),

    AV_PIX_FMT_GBRPF32BE(AV_PIX_FMT_GBRP.value + 104),

    AV_PIX_FMT_GBRPF32LE(AV_PIX_FMT_GBRP.value + 105),

    AV_PIX_FMT_GBRAPF32BE(AV_PIX_FMT_GBRP.value + 106),

    AV_PIX_FMT_GBRAPF32LE(AV_PIX_FMT_GBRP.value + 107),

    AV_PIX_FMT_DRM_PRIME(AV_PIX_FMT_GBRP.value + 108),

    AV_PIX_FMT_OPENCL(AV_PIX_FMT_GBRP.value + 109),

    AV_PIX_FMT_GRAY14BE(AV_PIX_FMT_GBRP.value + 110),

    AV_PIX_FMT_GRAY14LE(AV_PIX_FMT_GBRP.value + 111),

    AV_PIX_FMT_GRAYF32BE(AV_PIX_FMT_GBRP.value + 112),

    AV_PIX_FMT_GRAYF32LE(AV_PIX_FMT_GBRP.value + 113),

    AV_PIX_FMT_YUVA422P12BE(AV_PIX_FMT_GBRP.value + 114),

    AV_PIX_FMT_YUVA422P12LE(AV_PIX_FMT_GBRP.value + 115),

    AV_PIX_FMT_YUVA444P12BE(AV_PIX_FMT_GBRP.value + 116),

    AV_PIX_FMT_YUVA444P12LE(AV_PIX_FMT_GBRP.value + 117),

    AV_PIX_FMT_NV24(AV_PIX_FMT_GBRP.value + 118),

    AV_PIX_FMT_NV42(AV_PIX_FMT_GBRP.value + 119),

    AV_PIX_FMT_VULKAN(AV_PIX_FMT_GBRP.value + 120),

    AV_PIX_FMT_Y210BE(AV_PIX_FMT_GBRP.value + 121),

    AV_PIX_FMT_Y210LE(AV_PIX_FMT_GBRP.value + 122),

    AV_PIX_FMT_X2RGB10LE(AV_PIX_FMT_GBRP.value + 123),

    AV_PIX_FMT_X2RGB10BE(AV_PIX_FMT_GBRP.value + 124),

    AV_PIX_FMT_X2BGR10LE(AV_PIX_FMT_GBRP.value + 125),

    AV_PIX_FMT_X2BGR10BE(AV_PIX_FMT_GBRP.value + 126),

    AV_PIX_FMT_P210BE(AV_PIX_FMT_GBRP.value + 127),

    AV_PIX_FMT_P210LE(AV_PIX_FMT_GBRP.value + 128),

    AV_PIX_FMT_P410BE(AV_PIX_FMT_GBRP.value + 129),

    AV_PIX_FMT_P410LE(AV_PIX_FMT_GBRP.value + 130),

    AV_PIX_FMT_P216BE(AV_PIX_FMT_GBRP.value + 131),

    AV_PIX_FMT_P216LE(AV_PIX_FMT_GBRP.value + 132),

    AV_PIX_FMT_P416BE(AV_PIX_FMT_GBRP.value + 133),

    AV_PIX_FMT_P416LE(AV_PIX_FMT_GBRP.value + 134),

    AV_PIX_FMT_VUYA(AV_PIX_FMT_GBRP.value + 135),

    AV_PIX_FMT_RGBAF16BE(AV_PIX_FMT_GBRP.value + 136),

    AV_PIX_FMT_RGBAF16LE(AV_PIX_FMT_GBRP.value + 137),

    AV_PIX_FMT_VUYX(AV_PIX_FMT_GBRP.value + 138),

    AV_PIX_FMT_P012LE(AV_PIX_FMT_GBRP.value + 139),

    AV_PIX_FMT_P012BE(AV_PIX_FMT_GBRP.value + 140),

    AV_PIX_FMT_Y212BE(AV_PIX_FMT_GBRP.value + 141),

    AV_PIX_FMT_Y212LE(AV_PIX_FMT_GBRP.value + 142),

    AV_PIX_FMT_XV30BE(AV_PIX_FMT_GBRP.value + 143),

    AV_PIX_FMT_XV30LE(AV_PIX_FMT_GBRP.value + 144),

    AV_PIX_FMT_XV36BE(AV_PIX_FMT_GBRP.value + 145),

    AV_PIX_FMT_XV36LE(AV_PIX_FMT_GBRP.value + 146),

    AV_PIX_FMT_RGBF32BE(AV_PIX_FMT_GBRP.value + 147),

    AV_PIX_FMT_RGBF32LE(AV_PIX_FMT_GBRP.value + 148),

    AV_PIX_FMT_RGBAF32BE(AV_PIX_FMT_GBRP.value + 149),

    AV_PIX_FMT_RGBAF32LE(AV_PIX_FMT_GBRP.value + 150),

    AV_PIX_FMT_P212BE(AV_PIX_FMT_GBRP.value + 151),

    AV_PIX_FMT_P212LE(AV_PIX_FMT_GBRP.value + 152),

    AV_PIX_FMT_P412BE(AV_PIX_FMT_GBRP.value + 153),

    AV_PIX_FMT_P412LE(AV_PIX_FMT_GBRP.value + 154),

    AV_PIX_FMT_GBRAP14BE(AV_PIX_FMT_GBRP.value + 155),

    AV_PIX_FMT_GBRAP14LE(AV_PIX_FMT_GBRP.value + 156),

    AV_PIX_FMT_NB(AV_PIX_FMT_GBRP.value + 157)
}

public expect val AVPixelFormat.descriptor: AVPixelFormatDescriptor?