package dev.zt64.ffmpegkt.avutil

public enum class ColorPrimaries {
    AVCOL_PRI_RESERVED0,
    AVCOL_PRI_BT709,
    AVCOL_PRI_UNSPECIFIED,
    AVCOL_PRI_RESERVED,
    AVCOL_PRI_BT470M,
    AVCOL_PRI_BT470BG,
    AVCOL_PRI_SMPTE170M,
    AVCOL_PRI_SMPTE240M,
    AVCOL_PRI_FILM,
    AVCOL_PRI_BT2020,
    AVCOL_PRI_SMPTE428,
    AVCOL_PRI_SMPTEST428_1,
    AVCOL_PRI_SMPTE431,
    AVCOL_PRI_SMPTE432,
    AVCOL_PRI_EBU3213,
    AVCOL_PRI_JEDEC_P22
}