package dev.zt64.ffmpegkt.avcodec

import dev.zt64.ffmpegkt.avutil.AVMediaType
import kotlin.jvm.JvmInline

/**
 * Codec IDs are an integer value that identifies a codec.
 *
 * @constructor Should not be used directly. Use the predefined values in the companion object.
 */
@JvmInline
public value class AVCodecID(public val num: Int) {
    @Suppress("ktlint:standard:backing-property-naming", "ObjectPropertyName", "SpellCheckingInspection")
    public companion object {
        public val NONE: AVCodecID = AVCodecID(0)

        /* video codecs */
        public val MPEG1VIDEO: AVCodecID = AVCodecID(1)

        /** preferred ID for MPEG-1/2 video decoding */
        public val MPEG2VIDEO: AVCodecID = AVCodecID(2)
        public val H261: AVCodecID = AVCodecID(3)
        public val H263: AVCodecID = AVCodecID(4)
        public val RV10: AVCodecID = AVCodecID(5)
        public val RV20: AVCodecID = AVCodecID(6)
        public val MJPEG: AVCodecID = AVCodecID(7)
        public val MJPEGB: AVCodecID = AVCodecID(8)
        public val LJPEG: AVCodecID = AVCodecID(9)
        public val SP5X: AVCodecID = AVCodecID(10)
        public val JPEGLS: AVCodecID = AVCodecID(11)
        public val MPEG4: AVCodecID = AVCodecID(12)

        public val RAWVIDEO: AVCodecID = AVCodecID(13)
        public val MSMPEG4V1: AVCodecID = AVCodecID(14)
        public val MSMPEG4V2: AVCodecID = AVCodecID(15)
        public val MSMPEG4V3: AVCodecID = AVCodecID(16)
        public val WMV1: AVCodecID = AVCodecID(17)
        public val WMV2: AVCodecID = AVCodecID(18)
        public val H263P: AVCodecID = AVCodecID(19)
        public val H263I: AVCodecID = AVCodecID(20)
        public val FLV1: AVCodecID = AVCodecID(21)
        public val SVQ1: AVCodecID = AVCodecID(22)
        public val SVQ3: AVCodecID = AVCodecID(23)
        public val DVVIDEO: AVCodecID = AVCodecID(24)
        public val HUFFYUV: AVCodecID = AVCodecID(25)
        public val CYUV: AVCodecID = AVCodecID(26)
        public val H264: AVCodecID = AVCodecID(27)
        public val INDEO3: AVCodecID = AVCodecID(28)
        public val VP3: AVCodecID = AVCodecID(29)
        public val THEORA: AVCodecID = AVCodecID(30)
        public val ASV1: AVCodecID = AVCodecID(31)
        public val ASV2: AVCodecID = AVCodecID(32)
        public val FFV1: AVCodecID = AVCodecID(33)
        public val _4XM: AVCodecID = AVCodecID(34)
        public val VCR1: AVCodecID = AVCodecID(35)
        public val CLJR: AVCodecID = AVCodecID(36)
        public val MDEC: AVCodecID = AVCodecID(37)
        public val ROQ: AVCodecID = AVCodecID(38)
        public val INTERPLAY_VIDEO: AVCodecID = AVCodecID(39)
        public val XAN_WC3: AVCodecID = AVCodecID(40)
        public val XAN_WC4: AVCodecID = AVCodecID(41)
        public val RPZA: AVCodecID = AVCodecID(42)
        public val CINEPAK: AVCodecID = AVCodecID(43)
        public val WS_VQA: AVCodecID = AVCodecID(44)
        public val MSRLE: AVCodecID = AVCodecID(45)
        public val MSVIDEO1: AVCodecID = AVCodecID(46)
        public val IDCIN: AVCodecID = AVCodecID(47)
        public val _8BPS: AVCodecID = AVCodecID(48)
        public val SMC: AVCodecID = AVCodecID(49)
        public val FLIC: AVCodecID = AVCodecID(50)
        public val TRUEMOTION1: AVCodecID = AVCodecID(51)
        public val VMDVIDEO: AVCodecID = AVCodecID(52)
        public val MSZH: AVCodecID = AVCodecID(53)
        public val ZLIB: AVCodecID = AVCodecID(54)
        public val QTRLE: AVCodecID = AVCodecID(55)
        public val SNOW: AVCodecID = AVCodecID(56)
        public val TSCC: AVCodecID = AVCodecID(57)
        public val ULTI: AVCodecID = AVCodecID(58)
        public val QDRAW: AVCodecID = AVCodecID(59)
        public val VIXL: AVCodecID = AVCodecID(60)
        public val QPEG: AVCodecID = AVCodecID(61)
        public val XVID: AVCodecID = AVCodecID(62)
        public val PNG: AVCodecID = AVCodecID(63)
        public val PPM: AVCodecID = AVCodecID(64)
        public val PBM: AVCodecID = AVCodecID(65)
        public val PGM: AVCodecID = AVCodecID(66)
        public val PGMYUV: AVCodecID = AVCodecID(67)
        public val PAM: AVCodecID = AVCodecID(68)
        public val FFVHUFF: AVCodecID = AVCodecID(69)
        public val RV30: AVCodecID = AVCodecID(70)
        public val RV40: AVCodecID = AVCodecID(71)
        public val VC1: AVCodecID = AVCodecID(72)
        public val WMV3: AVCodecID = AVCodecID(73)
        public val LOCO: AVCodecID = AVCodecID(74)
        public val WNV1: AVCodecID = AVCodecID(75)
        public val AASC: AVCodecID = AVCodecID(76)
        public val INDEO2: AVCodecID = AVCodecID(77)
        public val FRAPS: AVCodecID = AVCodecID(78)
        public val TRUEMOTION2: AVCodecID = AVCodecID(79)
        public val BMP: AVCodecID = AVCodecID(80)
        public val CSCD: AVCodecID = AVCodecID(81)
        public val MMVIDEO: AVCodecID = AVCodecID(82)
        public val ZMBV: AVCodecID = AVCodecID(83)
        public val AVS: AVCodecID = AVCodecID(84)
        public val SMACKVIDEO: AVCodecID = AVCodecID(85)
        public val NUV: AVCodecID = AVCodecID(86)
        public val KMVC: AVCodecID = AVCodecID(87)
        public val FLASHSV: AVCodecID = AVCodecID(88)
        public val CAVS: AVCodecID = AVCodecID(89)
        public val JPEG2000: AVCodecID = AVCodecID(90)
        public val VMNC: AVCodecID = AVCodecID(91)
        public val VP5: AVCodecID = AVCodecID(92)
        public val VP6: AVCodecID = AVCodecID(93)
        public val VP6F: AVCodecID = AVCodecID(94)
        public val TARGA: AVCodecID = AVCodecID(95)
        public val DSICINVIDEO: AVCodecID = AVCodecID(96)
        public val TIERTEXSEQVIDEO: AVCodecID = AVCodecID(97)
        public val TIFF: AVCodecID = AVCodecID(98)
        public val GIF: AVCodecID = AVCodecID(99)
        public val FFH264: AVCodecID = AVCodecID(100)
        public val DXA: AVCodecID = AVCodecID(101)
        public val DNXHD: AVCodecID = AVCodecID(102)
        public val THP: AVCodecID = AVCodecID(103)
        public val SGI: AVCodecID = AVCodecID(104)
        public val C93: AVCodecID = AVCodecID(105)
        public val BETHSOFTVID: AVCodecID = AVCodecID(106)
        public val PTX: AVCodecID = AVCodecID(107)
        public val TXD: AVCodecID = AVCodecID(108)
        public val VP6A: AVCodecID = AVCodecID(109)
        public val AMV: AVCodecID = AVCodecID(110)
        public val VB: AVCodecID = AVCodecID(111)
        public val PCX: AVCodecID = AVCodecID(112)
        public val SUNRAST: AVCodecID = AVCodecID(113)
        public val INDEO4: AVCodecID = AVCodecID(114)
        public val INDEO5: AVCodecID = AVCodecID(115)
        public val MIMIC: AVCodecID = AVCodecID(116)
        public val RL2: AVCodecID = AVCodecID(117)
        public val _8SVX_EXP: AVCodecID = AVCodecID(118)
        public val _8SVX_FIB: AVCodecID = AVCodecID(119)
        public val ESCAPE124: AVCodecID = AVCodecID(120)
        public val DIRAC: AVCodecID = AVCodecID(121)
        public val BFI: AVCodecID = AVCodecID(122)
        public val CMV: AVCodecID = AVCodecID(123)
        public val MOTIONPIXELS: AVCodecID = AVCodecID(124)
        public val TGV: AVCodecID = AVCodecID(125)
        public val TGQ: AVCodecID = AVCodecID(126)
        public val TQI: AVCodecID = AVCodecID(127)
        public val AURA: AVCodecID = AVCodecID(128)
        public val AURA2: AVCodecID = AVCodecID(129)
        public val V210X: AVCodecID = AVCodecID(130)
        public val TMV: AVCodecID = AVCodecID(131)
        public val V210: AVCodecID = AVCodecID(132)
        public val DPX: AVCodecID = AVCodecID(133)
        public val MAD: AVCodecID = AVCodecID(134)
        public val FRWU: AVCodecID = AVCodecID(135)
        public val FLASHSV2: AVCodecID = AVCodecID(136)
        public val CDGRAPHICS: AVCodecID = AVCodecID(137)
        public val R210: AVCodecID = AVCodecID(138)
        public val ANM: AVCodecID = AVCodecID(139)
        public val BINKVIDEO: AVCodecID = AVCodecID(140)
        public val IFF_ILBM: AVCodecID = AVCodecID(141)
        public val IFF_BYTERUN1: AVCodecID = AVCodecID(142)
        public val KGV1: AVCodecID = AVCodecID(143)
        public val YOP: AVCodecID = AVCodecID(144)
        public val VP8: AVCodecID = AVCodecID(145)

        /* various PCM "codecs" */
        public val PCM_S16LE: AVCodecID = AVCodecID(0x10000)
        public val PCM_S16BE: AVCodecID = AVCodecID(0x10001)
        public val PCM_U16LE: AVCodecID = AVCodecID(0x10002)
        public val PCM_U16BE: AVCodecID = AVCodecID(0x10003)
        public val PCM_S8: AVCodecID = AVCodecID(0x10004)
        public val PCM_U8: AVCodecID = AVCodecID(0x10005)
        public val PCM_MULAW: AVCodecID = AVCodecID(0x10006)
        public val PCM_ALAW: AVCodecID = AVCodecID(0x10007)
        public val PCM_S32LE: AVCodecID = AVCodecID(0x10008)
        public val PCM_S32BE: AVCodecID = AVCodecID(0x10009)
        public val PCM_U32LE: AVCodecID = AVCodecID(0x1000A)
        public val PCM_U32BE: AVCodecID = AVCodecID(0x1000B)
        public val PCM_S24LE: AVCodecID = AVCodecID(0x1000C)
        public val PCM_S24BE: AVCodecID = AVCodecID(0x1000D)
        public val PCM_U24LE: AVCodecID = AVCodecID(0x1000E)
        public val PCM_U24BE: AVCodecID = AVCodecID(0x1000F)
        public val PCM_S24DAUD: AVCodecID = AVCodecID(0x10010)
        public val PCM_ZORK: AVCodecID = AVCodecID(0x10011)
        public val PCM_S16LE_PLANAR: AVCodecID = AVCodecID(0x10012)
        public val PCM_DVD: AVCodecID = AVCodecID(0x10013)
        public val PCM_F32BE: AVCodecID = AVCodecID(0x10014)
        public val PCM_F32LE: AVCodecID = AVCodecID(0x10015)
        public val PCM_F64BE: AVCodecID = AVCodecID(0x10016)
        public val PCM_F64LE: AVCodecID = AVCodecID(0x10017)
        public val PCM_BLURAY: AVCodecID = AVCodecID(0x10018)

        /* various ADPCM codecs */
        public val ADPCM_IMA_QT: AVCodecID = AVCodecID(0x11000)
        public val ADPCM_IMA_WAV: AVCodecID = AVCodecID(0x11001)
        public val ADPCM_IMA_DK3: AVCodecID = AVCodecID(0x11002)
        public val ADPCM_IMA_DK4: AVCodecID = AVCodecID(0x11003)
        public val ADPCM_IMA_WS: AVCodecID = AVCodecID(0x11004)
        public val ADPCM_IMA_SMJPEG: AVCodecID = AVCodecID(0x11005)
        public val ADPCM_MS: AVCodecID = AVCodecID(0x11006)
        public val ADPCM_4XM: AVCodecID = AVCodecID(0x11007)
        public val ADPCM_XA: AVCodecID = AVCodecID(0x11008)
        public val ADPCM_ADX: AVCodecID = AVCodecID(0x11009)
        public val ADPCM_EA: AVCodecID = AVCodecID(0x1100A)
        public val ADPCM_G726: AVCodecID = AVCodecID(0x1100B)
        public val ADPCM_CT: AVCodecID = AVCodecID(0x1100C)
        public val ADPCM_SWF: AVCodecID = AVCodecID(0x1100D)
        public val ADPCM_YAMAHA: AVCodecID = AVCodecID(0x1100E)
        public val ADPCM_SBPRO_4: AVCodecID = AVCodecID(0x1100F)
        public val ADPCM_SBPRO_3: AVCodecID = AVCodecID(0x11010)
        public val ADPCM_SBPRO_2: AVCodecID = AVCodecID(0x11011)
        public val ADPCM_THP: AVCodecID = AVCodecID(0x11012)
        public val ADPCM_IMA_AMV: AVCodecID = AVCodecID(0x11013)
        public val ADPCM_EA_R1: AVCodecID = AVCodecID(0x11014)
        public val ADPCM_EA_R3: AVCodecID = AVCodecID(0x11015)
        public val ADPCM_EA_R2: AVCodecID = AVCodecID(0x11016)
        public val ADPCM_IMA_EA_SEAD: AVCodecID = AVCodecID(0x11017)
        public val ADPCM_IMA_EA_EACS: AVCodecID = AVCodecID(0x11018)
        public val ADPCM_EA_XAS: AVCodecID = AVCodecID(0x11019)
        public val ADPCM_EA_MAXIS_XA: AVCodecID = AVCodecID(0x1101A)
        public val ADPCM_IMA_ISS: AVCodecID = AVCodecID(0x1101B)

        /* AMR */
        public val AMR_NB: AVCodecID = AVCodecID(0x12000)
        public val AMR_WB: AVCodecID = AVCodecID(0x12001)

        /* RealAudio codecs*/
        public val RA_144: AVCodecID = AVCodecID(0x13000)
        public val RA_288: AVCodecID = AVCodecID(0x13001)

        /* various DPCM codecs */
        public val ROQ_DPCM: AVCodecID = AVCodecID(0x14000)
        public val INTERPLAY_DPCM: AVCodecID = AVCodecID(0x14001)
        public val XAN_DPCM: AVCodecID = AVCodecID(0x14002)
        public val SOL_DPCM: AVCodecID = AVCodecID(0x14003)

        /* audio codecs */
        public val MP2: AVCodecID = AVCodecID(0x15000)

        /** preferred ID for decoding MPEG audio layer 1, 2 or 3 */
        public val MP3: AVCodecID = AVCodecID(0x15001)
        public val AAC: AVCodecID = AVCodecID(0x15002)
        public val AC3: AVCodecID = AVCodecID(0x15003)
        public val DTS: AVCodecID = AVCodecID(0x15004)
        public val VORBIS: AVCodecID = AVCodecID(0x15005)
        public val DVAUDIO: AVCodecID = AVCodecID(0x15006)
        public val WMAV1: AVCodecID = AVCodecID(0x15007)
        public val WMAV2: AVCodecID = AVCodecID(0x15008)
        public val MACE3: AVCodecID = AVCodecID(0x15009)
        public val MACE6: AVCodecID = AVCodecID(0x1500A)
        public val VMDAUDIO: AVCodecID = AVCodecID(0x1500B)
        public val SONIC: AVCodecID = AVCodecID(0x1500C)
        public val SONIC_LS: AVCodecID = AVCodecID(0x1500D)
        public val FLAC: AVCodecID = AVCodecID(0x1500E)
        public val MP3ADU: AVCodecID = AVCodecID(0x1500F)
        public val MP3ON4: AVCodecID = AVCodecID(0x15010)
        public val SHORTEN: AVCodecID = AVCodecID(0x15011)
        public val ALAC: AVCodecID = AVCodecID(0x15012)
        public val WESTWOOD_SND1: AVCodecID = AVCodecID(0x15013)

        /** as in Berlin toast format */
        public val GSM: AVCodecID = AVCodecID(0x15014)
        public val QDM2: AVCodecID = AVCodecID(0x15015)
        public val COOK: AVCodecID = AVCodecID(0x15016)
        public val TRUESPEECH: AVCodecID = AVCodecID(0x15017)
        public val TTA: AVCodecID = AVCodecID(0x15018)
        public val SMACKAUDIO: AVCodecID = AVCodecID(0x15019)
        public val QCELP: AVCodecID = AVCodecID(0x1501A)
        public val WAVPACK: AVCodecID = AVCodecID(0x1501B)
        public val DSICINAUDIO: AVCodecID = AVCodecID(0x1501C)
        public val IMC: AVCodecID = AVCodecID(0x1501D)
        public val MUSEPACK7: AVCodecID = AVCodecID(0x1501E)
        public val MLP: AVCodecID = AVCodecID(0x1501F)

        /** As found in WAV */
        public val GSM_MS: AVCodecID = AVCodecID(0x15020)
        public val ATRAC3: AVCodecID = AVCodecID(0x15021)
        public val VOXWARE: AVCodecID = AVCodecID(0x15022)
        public val APE: AVCodecID = AVCodecID(0x15023)
        public val NELLYMOSER: AVCodecID = AVCodecID(0x15024)
        public val MUSEPACK8: AVCodecID = AVCodecID(0x15025)
        public val SPEEX: AVCodecID = AVCodecID(0x15026)
        public val WMAVOICE: AVCodecID = AVCodecID(0x15027)
        public val WMAPRO: AVCodecID = AVCodecID(0x15028)
        public val WMALOSSLESS: AVCodecID = AVCodecID(0x15029)
        public val ATRAC3P: AVCodecID = AVCodecID(0x1502A)
        public val EAC3: AVCodecID = AVCodecID(0x1502B)
        public val SIPR: AVCodecID = AVCodecID(0x1502C)
        public val MP1: AVCodecID = AVCodecID(0x1502D)
        public val TWINVQ: AVCodecID = AVCodecID(0x1502E)
        public val TRUEHD: AVCodecID = AVCodecID(0x1502F)
        public val MP4ALS: AVCodecID = AVCodecID(0x15030)
        public val ATRAC1: AVCodecID = AVCodecID(0x15031)
        public val BINKAUDIO_RDFT: AVCodecID = AVCodecID(0x15032)
        public val BINKAUDIO_DCT: AVCodecID = AVCodecID(0x15033)

        /* subtitle codecs */
        public val DVD_SUBTITLE: AVCodecID = AVCodecID(0x17000)
        public val DVB_SUBTITLE: AVCodecID = AVCodecID(0x17001)
        public val TEXT: AVCodecID = AVCodecID(0x17002)
        public val XSUB: AVCodecID = AVCodecID(0x17003)
        public val SSA: AVCodecID = AVCodecID(0x17004)
        public val MOV_TEXT: AVCodecID = AVCodecID(0x17005)
        public val HDMV_PGS_SUBTITLE: AVCodecID = AVCodecID(0x17006)
        public val DVB_TELETEXT: AVCodecID = AVCodecID(0x17007)

        /* other specific kind of codecs (generally used for attachments) */
        public val TTF: AVCodecID = AVCodecID(0x18000)
        public val PROBE: AVCodecID = AVCodecID(0x19000)

        // _FAKE_ codec to indicate a raw MPEG-2 TS stream (only used by libavformat)
        public val MPEG2TS: AVCodecID = AVCodecID(0x20000)
    }

    override fun toString(): String = name
}

public expect val AVCodecID.type: AVMediaType
public expect val AVCodecID.name: String