name: Check

on:
  push:
    branches: [ main ]
    paths:
      - '**.kt'
      - '**.kts'
      - '**.cpp'
      - 'gradle.properties'
      - '.github/workflows/check.yml'
      - 'gradle/**'
  pull_request:
    branches: [ main ]
    paths:
      - '**.kt'
      - '**.kts'
      - '**.cpp'
      - 'gradle.properties'
      - '.github/workflows/check.yml'
      - 'gradle/**'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    name: "Check"
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Gradle Wrapper Validation
        uses: gradle/actions/wrapper-validation@v4

      - name: Cache konan directory
        uses: actions/cache@v4
        with:
          path: ~/.konan
          key: ${{ runner.os }}-konan-${{ hashFiles('**/build.gradle.kts') }}
          restore-keys: "${{ runner.os }}-konan-"

      - name: Check
        run: ./gradlew check